<a href="https://colab.research.google.com/github/Vijay203-Annanth/Python-programming-for-machine-learning-/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([[1,2,4], [5,8,7]])
print("Array created:\n",a)

Array created:
 [[1 2 4]
 [5 8 7]]


In [ ]:
#create a 3x4 array with all zeros
b=np.zeros((3,4))
print("Array with all zeros: \n",b)

Array with all zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#create a constant value array
c=np.full((3,3),6)
print("array with all 6's:\n",c)

array with all 6's:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#create an array with random values
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.67958279 0.80207742]
 [0.78536067 0.87405344]]


In [ ]:
#create a sequence of integer from 0 to 30 with step of 5
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [ ]:
#Reshaping 3x4 array in 2x2x3 array
arr=np.array([[1,2,3,4], [5,2,4,2], [1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array [4,3]:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array [4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [ ]:
#Flatten array
arr=np.array([[1,2,3,4], [5,2,4,2], [1,2,0,1]])
flarr=arr.flatten()
print("\nOriginal array: \n", arr)
print("\nFlatten array: \n", flarr)


Original array: 
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Flatten array: 
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4], [5,2,4,2], [1,2,0,1]])
print("\n No.od.dimensions:\n",arr.ndim)
print("\nShape of array:\n", arr.shape)
print("\nSize of array:\n", arr.size)
print("\nArray type:\n", arr.dtype)
newtype=arr.astype('f')
print("\nConverted array element: \n", newtype)
print("\nConverted array type: \n", newtype.dtype)


 No.od.dimensions:
 2

Shape of array:
 (3, 4)

Size of array:
 12

Array type:
 int64

Converted array element: 
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

Converted array type: 
 float32


In [15]:
#SLicing
import numpy as np
p=np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]])
print(p[3:0:-1])
print(p[2,0:21])
print(p[2:,2:])
print(p[3:,3:])
print(p[:,1])
c=p.astype('f')
print(c)
e=p.astype('i')
print(e)


[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8 9]
[[ 9]
 [12]
 [15]]
[]
[ 2  5  8 11 14]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
